import com.adarshr.gradle.testlogger.theme.ThemeType

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin on the JVM
    id("org.jetbrains.kotlin.jvm").version("1.3.10")
    id("com.adarshr.test-logger") version "1.5.0"
}

val test by tasks.getting(Test::class) {
    useJUnitPlatform { }
}

testlogger {
    theme = ThemeType.STANDARD
}

repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    // Use the Kotlin JDK 8 standard library
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation("org.slf4j:slf4j-simple:1.7.25")

    testCompile("io.kotlintest:kotlintest-runner-junit5:3.1.10")
}

